version: "3.8"

services:
  client:
    image: noureddinenh9/quiz-test-client
    container_name: quiz-test.client
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`quiz-test.nh9.dev`)"
      - "traefik.http.routers.client.entrypoints=web"
    networks:
      - web

networks:
  web:
    external:
      name: traefik-net
