version: "3.8"
services:
   quiz.client:
      build: .
      ports:
         - "5001:3000"
      volumes:
         - ./src:/app/src
      stdin_open: true
      tty: true

   npm:
      image: node:16.17.0-alpine
      working_dir: /app
      entrypoint: ["npm"]
      volumes:
         - ./:/app
