version: "3.8"

services:
  client:
    container_name: quiz-test.client
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quiz-test-client.rule=Host(`quiz-test.nh9.dev`)"
      - "traefik.http.routers.quiz-test-client.entrypoints=web"
    networks:
      - web

networks:
  web:
    external:
      name: traefik-net
